name = "104th Wolfsbattalion MC"
author = "Wolfsbattalion Team"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7dc5fcdda1697130830b3c746b2328d1ced43fabc4afbb43728c431c80eb729"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
