name = "104th Wolfsbattalion MC"
author = "Wolfsbattalion Team"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a553bbc7996891b823bee355fa04f284f50cb84712f4c79acba1a53a8a2604af"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
