name = "104th Wolfsbattalion MC"
author = "Wolfsbattalion Team"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a988be9440c4406693b333a2a4adede878e57c9368bcc7692007cd065ddea51d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
