name = "104th Wolfsbattalion MC"
author = "Wolfsbattalion Team"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76d8541e9c89de3e535e2437d8fec9fccc3886e1ee0d7a88b4da90929e5a569b"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
