name = "104th Wolfsbattalion MC"
author = "Wolfsbattalion Team"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06504b3804c1ade923781d5d4839835ac4c6711ff4129bf3d6ce47671a66658f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
