name = "104th Wolfsbattalion MC"
author = "Wolfsbattalion Team"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd6f143ecea0806112339adc186c694a432e16a62d5904f0310a68bdf2f130db"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
