name = "104th Wolfsbattalion MC"
author = "Wolfsbattalion Team"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7ef1bf38f3617b876000e46d35b88dca987e6dbbbc21188a6fe0202a1a633ce"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
